services:
  db:
    container_name: postgres
    image: postgres:14.1
    environment:
      POSTGRES_USER: cata
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - db
    restart: unless-stopped

  redis:
    image: "redis:7.0"
    container_name: "redis"
    ports:
      - 6379:6379

networks:
  db:
    driver: bridge

volumes:
  db: