services:
  db:
    container_name: postgres
    image: postgres:14.1
    environment:
      POSTGRES_USER: cata
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - db
    restart: unless-stopped

  keycloak:
    image: quay.io/keycloak/keycloak
    container_name: keycloak
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://db:5432/keycloak
      KC_DB_USERNAME: cata
      KC_DB_PASSWORD: password

      KC_HOSTNAME: localhost
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_HTTPS: false

      KC_LOG_LEVEL: info
      KC_METRICS_ENABLED: true
      KC_HEALTH_ENABLED: true
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: start-dev
    depends_on:
      - db
    ports:
      - 8080:8080
    networks:
      - db

  redis:
    image: "redis:7.0"
    container_name: "redis"
    ports:
      - 6379:6379

networks:
  db:
    driver: bridge

volumes:
  db: