server:
  port: 8222

eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true

spring:
  application:
    name: gateway_service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: users
          uri: http://localhost:8010
          predicates:
            - Path=/users/**
          filters:
            - PrefixPath=/api/v1