server:
  port: 8222

eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true

spring:
  application:
    name: gateway_service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      default-filters:
        - TokenRelay=
      routes:
        - id: users
          uri: http://localhost:8010
          predicates:
            - Path=/users/**
          filters:
            - PrefixPath=/api/v1
        - id: hotels
          uri: http://localhost:8020
          predicates:
            - Path=/hotels/**
          filters:
            - PrefixPath=/api/v1
        - id: bookings
          uri: http://localhost:8030
          predicates:
            - Path=/bookings/**
          filters:
            - PrefixPath=/api/v1
        - id: search
          uri: http://localhost:8040
          predicates:
            - Path=/search/**
          filters:
            - PrefixPath=/api/v1
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/realms/Booking-System/protocol/openid-connect/certs
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/Booking-System
        registration:
          backend:
            provider: keycloak
            client-id: backend
            client-secret: 6khInHEwAiSmemZvgZWPRCfLUQBuuidf
            authorization-grant-type: authorization_code
            scope: openid