server:
  port: 8010

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: user_service
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379
    time-to-live: 60000
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/realms/Booking-System/protocol/openid-connect/certs